# Generated by Django 5.2.5 on 2025-08-19 23:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuoyStation',
            fields=[
                ('station_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('location_description', models.CharField(blank=True, max_length=200)),
                ('exposure_type', models.CharField(choices=[('exposed', 'Exposed Atlantic'), ('coastal', 'Coastal/Sheltered'), ('intermediate', 'Intermediate Exposure'), ('variable', 'Variable Conditions'), ('unique', 'Unique Location')], default='intermediate', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['station_id'],
            },
        ),
        migrations.CreateModel(
            name='QCParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('default_min', models.FloatField(blank=True, null=True)),
                ('default_max', models.FloatField(blank=True, null=True)),
                ('default_spike_threshold', models.FloatField(blank=True, null=True)),
                ('parameter_type', models.CharField(choices=[('environmental', 'Environmental'), ('wave', 'Wave'), ('water', 'Water Quality')], default='environmental', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['parameter_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QCProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=50, unique=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qc_api.buoystation')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QCResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('total_records', models.IntegerField()),
                ('qc_complete_records', models.IntegerField()),
                ('qc_completion_rate', models.FloatField()),
                ('processing_date', models.DateTimeField(auto_now=True)),
                ('csv_file_path', models.CharField(blank=True, max_length=500)),
                ('report_md_path', models.CharField(blank=True, max_length=500)),
                ('report_pdf_path', models.CharField(blank=True, max_length=500)),
                ('visualization_path', models.CharField(blank=True, max_length=500)),
                ('issues_summary', models.JSONField(blank=True, default=dict)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qc_api.buoystation')),
            ],
            options={
                'ordering': ['station', '-year'],
                'unique_together': {('station', 'year')},
            },
        ),
        migrations.CreateModel(
            name='StationQCLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('spike_threshold', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qc_api.qcparameter')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qc_api.buoystation')),
            ],
            options={
                'ordering': ['station', 'parameter__parameter_type', 'parameter__name'],
                'unique_together': {('station', 'parameter')},
            },
        ),
    ]
