# Generated by Django 5.2.6 on 2025-09-30 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QCConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('total_comparisons', models.IntegerField(default=0)),
                ('confirmed_records', models.IntegerField(default=0)),
                ('deviation_records', models.IntegerField(default=0)),
                ('confirmation_rate', models.FloatField(default=0.0, help_text='Percentage of confirmed records')),
                ('air_pressure_confirmation', models.FloatField(blank=True, null=True)),
                ('air_temp_confirmation', models.FloatField(blank=True, null=True)),
                ('wind_speed_confirmation', models.FloatField(blank=True, null=True)),
                ('wave_height_confirmation', models.FloatField(blank=True, null=True)),
                ('sea_temp_confirmation', models.FloatField(blank=True, null=True)),
                ('mean_absolute_error', models.JSONField(blank=True, default=dict, help_text='MAE for each parameter')),
                ('root_mean_square_error', models.JSONField(blank=True, default=dict, help_text='RMSE for each parameter')),
                ('correlation_coefficient', models.JSONField(blank=True, default=dict, help_text='Correlation for each parameter')),
                ('third_party_source', models.CharField(default='era5', max_length=50)),
                ('analysis_date', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('qc_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qc_api.qcresult')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qc_api.buoystation')),
            ],
            options={
                'ordering': ['station', '-year'],
                'unique_together': {('station', 'year', 'third_party_source')},
            },
        ),
        migrations.CreateModel(
            name='ThirdPartyBuoyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('source', models.CharField(choices=[('era5', 'ERA5 Reanalysis'), ('met_eireann', 'Met Éireann'), ('noaa', 'NOAA'), ('copernicus', 'Copernicus Marine Service'), ('other', 'Other Source')], default='era5', max_length=50)),
                ('air_pressure', models.FloatField(blank=True, help_text='Air pressure (hPa)', null=True)),
                ('air_temperature', models.FloatField(blank=True, help_text='Air temperature (°C)', null=True)),
                ('humidity', models.FloatField(blank=True, help_text='Relative humidity (%)', null=True)),
                ('wind_speed', models.FloatField(blank=True, help_text='Wind speed (knots)', null=True)),
                ('wind_direction', models.FloatField(blank=True, help_text='Wind direction (degrees)', null=True)),
                ('wind_gust', models.FloatField(blank=True, help_text='Wind gust (knots)', null=True)),
                ('significant_wave_height', models.FloatField(blank=True, help_text='Significant wave height (m)', null=True)),
                ('max_wave_height', models.FloatField(blank=True, help_text='Maximum wave height (m)', null=True)),
                ('wave_period', models.FloatField(blank=True, help_text='Wave period (s)', null=True)),
                ('wave_direction', models.FloatField(blank=True, help_text='Wave direction (degrees)', null=True)),
                ('sea_temperature', models.FloatField(blank=True, help_text='Sea surface temperature (°C)', null=True)),
                ('salinity', models.FloatField(blank=True, help_text='Salinity (ppt)', null=True)),
                ('data_quality', models.CharField(choices=[('good', 'Good Quality'), ('fair', 'Fair Quality'), ('poor', 'Poor Quality'), ('unknown', 'Unknown Quality')], default='unknown', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qc_api.buoystation')),
            ],
            options={
                'verbose_name_plural': 'Third Party Buoy Data',
                'ordering': ['station', '-timestamp'],
                'unique_together': {('station', 'timestamp', 'source')},
            },
        ),
    ]
